# Generated by Django 5.2.10 on 2026-01-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimalsCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[("cow", "Cow"), ("sheep", "Sheep"), ("goat", "Goat")],
                        max_length=15,
                    ),
                ),
                (
                    "track_id",
                    models.IntegerField(
                        help_text="trekerdan olingan takrorlanmas (unikal) identifikator"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Animal Count",
                "verbose_name_plural": "Animals Count",
                "ordering": ["-timestamp"],
                "unique_together": {("animal_type", "track_id")},
            },
        ),
    ]
